name: Deploy-DEV

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - 'release/*'

  push:
    branches:
      - 'main'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      whatIf:
        description: 'Enable WhatIf Mode'
        type: boolean
        required: true
        default: false

env:
  PROFILE: TaxiTrips
  PBITOOLS_EffectiveDate: 2022-11-06

jobs:
  Deployment:
    runs-on: ubuntu-latest
    environment: Development
    container:
      image: ghcr.io/pbi-tools/pbi-tools-core:1.0.0-rc.2_preview.5

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: pbi-tools info
        run: |
          /app/pbi-tools/pbi-tools.core info

      - name: pbi-tools deploy (WhatIf)
        if: ${{ github.event.inputs.whatIf == 'true' }}
        run: |
          /app/pbi-tools/pbi-tools.core deploy . "$PROFILE" -whatIf
        env:
          PBI_CLIENT_SECRET: ${{ secrets.PBI_CLIENT_SECRET }}

      - name: pbi-tools deploy
        if: ${{ github.event.inputs.whatIf != 'true' }}
        run: |
          /app/pbi-tools/pbi-tools.core deploy . "$PROFILE"
        env:
          PBI_CLIENT_SECRET: ${{ secrets.PBI_CLIENT_SECRET }}
          SQL_USERNAME: ${{ secrets.SQL_USERNAME }}
          SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}

      - name: 'Upload Artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: .artifacts/**/*.*
